# A simple configable broadcast plugin created by: Snicser
# Config settings -  These are the default settings, you could change this settings in whatever you like.

#If the player has no permissions to broadcast
NO_PERMISSIONS: '&cYou do not have the permissions to excute this command.'

#Broadcast command permission
BROADCAST_PERMISSION: 'simplebroadcaster.use'

#BroadcastCommand prefix - example: [PREFIX] Message
PREFIX: '&f[&4&lBroadcast&r&f] &r'