name: SimpleBroadcaster
version: 2.0.0
main: nl.snicser.simplebroadcaster.SimpleBroadcaster
authors: [Snicser]
description: An custom configable broadcast plugin

commands:
  broadcast:
    description: BroadcastCommand a message
    aliases: [bc]
